// Generated by gencpp from file autoturtle/Path.msg
// DO NOT EDIT!


#ifndef AUTOTURTLE_MESSAGE_PATH_H
#define AUTOTURTLE_MESSAGE_PATH_H

#include <ros/service_traits.h>


#include <autoturtle/PathRequest.h>
#include <autoturtle/PathResponse.h>


namespace autoturtle
{

struct Path
{

typedef PathRequest Request;
typedef PathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Path
} // namespace autoturtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autoturtle::Path > {
  static const char* value()
  {
    return "d32b3108e0653dfb8af9c9692bc47b31";
  }

  static const char* value(const ::autoturtle::Path&) { return value(); }
};

template<>
struct DataType< ::autoturtle::Path > {
  static const char* value()
  {
    return "autoturtle/Path";
  }

  static const char* value(const ::autoturtle::Path&) { return value(); }
};


// service_traits::MD5Sum< ::autoturtle::PathRequest> should match
// service_traits::MD5Sum< ::autoturtle::Path >
template<>
struct MD5Sum< ::autoturtle::PathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autoturtle::Path >::value();
  }
  static const char* value(const ::autoturtle::PathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autoturtle::PathRequest> should match
// service_traits::DataType< ::autoturtle::Path >
template<>
struct DataType< ::autoturtle::PathRequest>
{
  static const char* value()
  {
    return DataType< ::autoturtle::Path >::value();
  }
  static const char* value(const ::autoturtle::PathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autoturtle::PathResponse> should match
// service_traits::MD5Sum< ::autoturtle::Path >
template<>
struct MD5Sum< ::autoturtle::PathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autoturtle::Path >::value();
  }
  static const char* value(const ::autoturtle::PathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autoturtle::PathResponse> should match
// service_traits::DataType< ::autoturtle::Path >
template<>
struct DataType< ::autoturtle::PathResponse>
{
  static const char* value()
  {
    return DataType< ::autoturtle::Path >::value();
  }
  static const char* value(const ::autoturtle::PathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOTURTLE_MESSAGE_PATH_H
