// Generated by gencpp from file autoturtle/PathResponse.msg
// DO NOT EDIT!


#ifndef AUTOTURTLE_MESSAGE_PATHRESPONSE_H
#define AUTOTURTLE_MESSAGE_PATHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autoturtle
{
template <class ContainerAllocator>
struct PathResponse_
{
  typedef PathResponse_<ContainerAllocator> Type;

  PathResponse_()
    : path()  {
    }
  PathResponse_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::autoturtle::PathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoturtle::PathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PathResponse_

typedef ::autoturtle::PathResponse_<std::allocator<void> > PathResponse;

typedef boost::shared_ptr< ::autoturtle::PathResponse > PathResponsePtr;
typedef boost::shared_ptr< ::autoturtle::PathResponse const> PathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoturtle::PathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoturtle::PathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autoturtle::PathResponse_<ContainerAllocator1> & lhs, const ::autoturtle::PathResponse_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autoturtle::PathResponse_<ContainerAllocator1> & lhs, const ::autoturtle::PathResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autoturtle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autoturtle::PathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoturtle::PathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoturtle::PathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoturtle::PathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoturtle::PathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoturtle::PathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoturtle::PathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d00cd540af97efeb6b1589112fab63e";
  }

  static const char* value(const ::autoturtle::PathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d00cd540af97efeULL;
  static const uint64_t static_value2 = 0xb6b1589112fab63eULL;
};

template<class ContainerAllocator>
struct DataType< ::autoturtle::PathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoturtle/PathResponse";
  }

  static const char* value(const ::autoturtle::PathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoturtle::PathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string path\n"
"# int32[] path\n"
;
  }

  static const char* value(const ::autoturtle::PathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoturtle::PathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoturtle::PathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoturtle::PathResponse_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOTURTLE_MESSAGE_PATHRESPONSE_H
