// Generated by gencpp from file autoturtle/PathRequest.msg
// DO NOT EDIT!


#ifndef AUTOTURTLE_MESSAGE_PATHREQUEST_H
#define AUTOTURTLE_MESSAGE_PATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autoturtle
{
template <class ContainerAllocator>
struct PathRequest_
{
  typedef PathRequest_<ContainerAllocator> Type;

  PathRequest_()
    : start()
    , stop()  {
    }
  PathRequest_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , stop(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _start_type;
  _start_type start;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _stop_type;
  _stop_type stop;





  typedef boost::shared_ptr< ::autoturtle::PathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoturtle::PathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PathRequest_

typedef ::autoturtle::PathRequest_<std::allocator<void> > PathRequest;

typedef boost::shared_ptr< ::autoturtle::PathRequest > PathRequestPtr;
typedef boost::shared_ptr< ::autoturtle::PathRequest const> PathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoturtle::PathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoturtle::PathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autoturtle::PathRequest_<ContainerAllocator1> & lhs, const ::autoturtle::PathRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start &&
    lhs.stop == rhs.stop;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autoturtle::PathRequest_<ContainerAllocator1> & lhs, const ::autoturtle::PathRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autoturtle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autoturtle::PathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoturtle::PathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoturtle::PathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoturtle::PathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoturtle::PathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoturtle::PathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoturtle::PathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0568d4421a7f52d03eeb3cde18aa062";
  }

  static const char* value(const ::autoturtle::PathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0568d4421a7f52dULL;
  static const uint64_t static_value2 = 0x03eeb3cde18aa062ULL;
};

template<class ContainerAllocator>
struct DataType< ::autoturtle::PathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoturtle/PathRequest";
  }

  static const char* value(const ::autoturtle::PathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoturtle::PathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] start\n"
"int32[] stop\n"
;
  }

  static const char* value(const ::autoturtle::PathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoturtle::PathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoturtle::PathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoturtle::PathRequest_<ContainerAllocator>& v)
  {
    s << indent << "start[]" << std::endl;
    for (size_t i = 0; i < v.start.size(); ++i)
    {
      s << indent << "  start[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.start[i]);
    }
    s << indent << "stop[]" << std::endl;
    for (size_t i = 0; i < v.stop.size(); ++i)
    {
      s << indent << "  stop[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.stop[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOTURTLE_MESSAGE_PATHREQUEST_H
